### ISSUE TITLE
support SH4 devices 7111 and 7162

### ISSUE THREAD

**Issue by angelheart150** [gutosie/neoboot#3]
dear gutosie

could you please support SH4 devices 7111 and 7162 ?

we need to use the genus plugin neoboot 

please 

thanks

**Comment by gutosie** [comment]
HELLO
neoboot 9.XX and above requires pin

Install new version 9.XX
The vip code is not public
The code is just for you
If the code is made public, it will be changed
Please do not disclose your pin code to the public
The plugin can be duplicated on other forums but without entering pin code
Plugin is constantly being improved whenever possible
New version will have updates
Any errors in operation should be sent to the plugin developer
If you have any questions, please write to the email

Donate to the project by paying a voluntary amount .
If you want to make a donation and you do not have paypal, You can send to
the account number:
Kod SWIFT/BIC Bank Pekao: PKOPPLPW
IBAN: PL 95 1240 1851 1111 0010 9537 0960
or:
Donate to the project by paying a voluntary amount for:
PayPal: ***@***.***

To enter the pin code, run the NeoBoot plugin and enter the code, There
will be no window to enter the pin code
Activate vip by entering code:    5476
Instructions for entering code in the photo attachment
You have a problem, delete vip version code 8900 and re-enter 5476
Always re-enter the code after updating
If the code changes ask for a new plugin author code

code to delete it:     9800
code to activate it:  5476

Good luck


czw., 30 wrz 2021 o 18:37 angelheart150 ***@***.***>
napisał(a):

**Comment by angelheart150** [comment]
dear gutosie

i am asking for sh4 devices support please help us with your plugin to work on our devices 

thanks in advance

**Comment by gutosie** [comment]
sh4,   not suporttet

pt., 1 paź 2021 o 16:24 angelheart150 ***@***.***> napisał(a):

**Comment by angelheart150** [comment]
thanks dear 

but i hope in future you can support us 

thanks
