### ISSUE TITLE
problem in plugin for vuduo4kse 

### ISSUE THREAD

**Issue by haithameng** [gutosie/neoboot#4]
![notepad1634857979492](https://user-images.githubusercontent.com/88112059/138372756-642bcd62-9150-44f7-82e0-6143895cafb5.jpg)
Dear bro gutosie
I have a problem, which is that the plugin does not appear in the list and this phrase appears, and I tried the commands 3

**Comment by gutosie** [comment]
My friend what receiver do you have ?

W dniu pt., 22.10.2021 o 03:08 haithameng ***@***.***>
napisał(a):

**Comment by haithameng** [comment]
receiver    vuduo 4kse

**Comment by haithameng** [comment]
When you convert the language of the device to English works, but does not work with the language of Arabic and there is a lot of suffering from the same problem.
