### ISSUE TITLE
code

### ISSUE THREAD

**Issue by haithameng** [gutosie/neoboot#5]
dear gutosie... 
Can you send the code?
and thanks bro.

**Comment by gutosie** [comment]
HELLO
neoboot 9.XX and above requires pin

Install new version 9.XX
The vip code is not public
The code is just for you
If the code is made public, it will be changed
Please do not disclose your pin code to the public
The plugin can be duplicated on other forums but without entering pin code
Plugin is constantly being improved whenever possible
New version will have updates
Any errors in operation should be sent to the plugin developer
If you have any questions, please write to the email

Donate to the project by paying a voluntary amount .
If you want to make a donation and you do not have paypal, You can send to
the account number:
Kod SWIFT/BIC Bank Pekao: PKOPPLPW
IBAN: PL 95 1240 1851 1111 0010 9537 0960
or:
Donate to the project by paying a voluntary amount for:
PayPal: ***@***.***

To enter the pin code, run the NeoBoot plugin and enter the code, There
will be no window to enter the pin code
Activate vip by entering code:    5476
Instructions for entering code in the photo attachment
You have a problem, delete vip version code 8900 and re-enter 5476
Always re-enter the code after updating
If the code changes ask for a new plugin author code

code to delete it:     9800
code to activate it:  5476

Good luck
NeoBoot Enigma2 Plugin by gutosi ( اقوى بلاغين لعمل الاقلاع المتعدد )
https://www.youtube.com/watch?v=x_dxBo25r14
https://www.youtube.com/watch?v=paCsJQuS8Bo


pon., 1 lis 2021 o 13:20 haithameng ***@***.***> napisał(a):

**Comment by haithameng** [comment]
thanks bro

**Comment by gutosie** [comment]
HELLO
neoboot 9.XX and above requires pin

Install new version 9.XX
The vip code is not public
The code is just for you
If the code is made public, it will be changed
Please do not disclose your pin code to the public
The plugin can be duplicated on other forums but without entering pin code
Plugin is constantly being improved whenever possible
New version will have updates
Any errors in operation should be sent to the plugin developer
If you have any questions, please write to the email

Donate to the project by paying a voluntary amount .
If you want to make a donation and you do not have paypal, You can send to
the account number:
Kod SWIFT/BIC Bank Pekao: PKOPPLPW
IBAN: PL 95 1240 1851 1111 0010 9537 0960
or:
Donate to the project by paying a voluntary amount for:
PayPal: ***@***.***

To enter the pin code, run the NeoBoot plugin and enter the code, There
will be no window to enter the pin code
Activate vip by entering code:    5476
Instructions for entering code in the photo attachment
You have a problem, delete vip version code 8900 and re-enter 5476
Always re-enter the code after updating
If the code changes ask for a new plugin author code

code to delete it:     9800
code to activate it:  5476

Good luck
NeoBoot Enigma2 Plugin by gutosi ( اقوى بلاغين لعمل الاقلاع المتعدد )
https://www.youtube.com/watch?v=x_dxBo25r14
https://www.youtube.com/watch?v=paCsJQuS8Bo

wt., 2 lis 2021 o 14:29 haithameng ***@***.***> napisał(a):
